# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
    auto_detect_solc = false
    bytecode_hash = "none"
    evm_version = "paris"
    gas_reports = ["*"]
    optimizer = true
    optimizer_runs = 200
    solc = "0.8.24"
    out = "out"
    src = "contracts"
    test = "test"
    script = "script"
    fs_permissions = [{ access = "read", path = "./" }]

[profile.ci]
    fuzz = { runs = 10_000 }

[rpc_endpoints]
    mainnet = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
