# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
    auto_detect_solc = false
    bytecode_hash = "none"
    evm_version = "paris"
    gas_reports = ["*"]
    optimizer = true
    optimizer_runs = 200
    solc = "0.8.24"
    out = "out"
    src = "contracts"
    test = "test"
    script = "script"

[profile.ci]
    fuzz = { runs = 10_000 }
    verbosity = 4
